services:
  # Base de données pour auth-service
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: postgres-auth
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - car-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base de données pour car-service
  postgres-car:
    image: postgres:15
    container_name: postgres-car
    environment:
      POSTGRES_DB: postgres-car
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_car_data:/var/lib/postgresql/data
    networks:
      - car-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base de données pour rental-service
  postgres-rental:
    image: postgres:15
    container_name: postgres-rental
    environment:
      POSTGRES_DB: postgres-rental
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_rental_data:/var/lib/postgresql/data
    networks:
      - car-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Server
  eureka-server:
    image: YassineMfa/car-management-system-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - car-network
    depends_on:
      postgres-auth:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # API Gateway
  api-gateway:
    image: YassineMfa/car-management-system-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - car-network
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Auth Service
  auth-service:
    image: YassineMfa/car-management-system-auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - car-network
    depends_on:
      - eureka-server
      - postgres-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/postgres-auth
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Car Service
  car-service:
    image: YassineMfa/car-management-system-car-service:latest
    container_name: car-service
    ports:
      - "8082:8082"
    networks:
      - car-network
    depends_on:
      - eureka-server
      - postgres-car
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-car:5432/postgres-car
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Rental Service
  rental-service:
    image: YassineMfa/car-management-system-rental-service:latest
    container_name: rental-service
    ports:
      - "8083:8083"
    networks:
      - car-network
    depends_on:
      - eureka-server
      - postgres-rental
      - car-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-rental:5432/postgres-rental
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      CAR_SERVICE_URL: http://car-service:8082

  # Frontend Application
  frontend:
    image: YassineMfa/car-management-system-frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - car-network
    depends_on:
      - api-gateway

networks:
  car-network:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_car_data:
  postgres_rental_data:
