# Port du service
server.port=8082

# Nom du service (important pour Eureka)
spring.application.name=car-service

# URL du serveur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/car_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=mySecretKeyForJwtGeneration

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Désactiver Spring Security temporairement
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Logging
logging.level.com.carmanagement.car=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Actuator pour Eureka
eureka.instance.health-check-url=http://localhost:8082/actuator/health
eureka.instance.status-page-url=http://localhost:8082/actuator/info
